# Generated by Django 3.2.25 on 2025-09-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('expires_in', models.DateTimeField()),
            ],
        ),
    ]
