# Generated by Django 3.2.25 on 2025-10-22 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationpin',
            name='authorization_pin',
            field=models.CharField(default='fadiya1234', max_length=50),
        ),
        migrations.CreateModel(
            name='MusicAuthorizationPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_pin', models.CharField(default='fadiya1234', max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
